name: CICD workflows

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v5

      # Setup python environmnet
      - name: Setup python environmnet
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      # Install Dependencies
      - name : Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov -r requirements.txt

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Checkout the repository
      - name: Checkout the repository
        uses: actions/checkout@v5

      # Docker login
      - name: DOcker login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # Build and push docker image
      - name: docker image build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/git-gist:${{github.run_number}}

          

     
